modLoader="javafml"
loaderVersion="${loader_version_range}"
license="MIT"
[[mods]]
modId="extrabotany"
version="0.0.1"
displayName="Extra Botany"
authors="${mod_authors}"
description='''It ports some flowers from ExtraBotany'''
[[dependencies.extrabotany]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.extrabotany]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.extrabotany]]
modId="botania"
mandatory=true
versionRange="(1.20.1-446,]"
ordering="NONE"
side="BOTH"
[[dependencies.extrabotany]]
modId="curios"
mandatory=true
versionRange="(5.9,]"
ordering="NONE"
side="BOTH"
[[dependencies.extrabotany]]
modId="patchouli"
mandatory=true
versionRange="(1.20.1-80,]"
ordering="NONE"
side="BOTH"
